name: InfraBuild

on: 
  push:
    branches:
      - main
    paths:
      - ./infra
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs:
  Plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: arn:aws:iam::086227530319:role/tf-role
          aws-region: us-east-1
          role-session-name: GitHubActions

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Run Terraform Plan
        run: terraform plan -out=tfplan 

      - name: Upload Terraform plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/tfplan
      